### ISSUE TITLE
Clarifying frequency of block size increases

### ISSUE THREAD

**Issue by bigreddmachine** [jgarzik/bip100#10]
Quote 1:

> ii. A new hardLimit is calculated at each difficult adjustment period (2016 blocks), and applies to the next 2016 blocks.

Quote 2:

> b. Votes are limited to +/- 20% of the current hardLimit.
> c. Sort the votes from the previous 12,000 blocks from lowest to highest.
> d. The raise value is defined as a vote for 2400th highest block (20th percentile).
> e. The lower value is defined as a vote for 9600th highest block (80th percentile).
> f. If the raise value is higher than current hardLimit, the new limit becomes the raise value.
> g. If the lower value is lower than current hardLimit, the new limit becomes the lower value.
> h. Otherwise, hardLimit is unchanged.

---

After a hardLimit adjustment at Block XXXXXX, can the hardLimit adjust again at Block XXXXXX+2016 (allowing reuse of voted from Blocks XXXXXX-9085 through XXXXXX-1)?

Or, are those votes note reusable, and is the next possible hardLimit adjustment at Block Block XXXXXX+12096?

_-- Apologies if my "XXX+" and "XXX-" numbers are off by +/- 1, but I think I marked them correctly._

**Comment by 1MichaS1** [comment]
My understanding is that Jeff just forgot to align the numbers in "Quote 2" after having introduced the 2016 blocks in "Quote 1" (which I find very reasonable). Here is my pull request to fix this:
https://github.com/jgarzik/bip100/pull/14

**Comment by 1MichaS1** [comment]
If it was really meant to be as it is currently written in BIP100 (namely updates every 2,016 blocks, but every time taking into account the last 12,000 blocks from that moment), then at least the "12,000" should be replaced by a multiple of 2,016 (e.g. 6 \* 2,016 = 12,096 blocks), because otherwise the voting scheme would be unfair by design in that not every vote would have the same weight:

With current description, the first 96 votes within each 2,016 blocks period would be considered in the next 5(!) block size limit adjustments, whereas the votes in the blocks 97..2,016 of a 2,016-block interval would be considered in the next 6(!) adjustment intervals. I.e. votes of blocks 97..2,016 have 20% more weight than the blocks 1..96. This is really odd and certainly should not remain like this.

However, even that could have strange effects. Example: Let's assume that block size limit (BSL) is already at 3 MB, and in this situation there occurs a temporary "anomaly" of miners, such that all miners vote for 1MB for 2420 blocks in a row. In this case, the 20% percentile threshold is surpassed, so BSL gets reduced by -20% (the cap of BIP100 for a single adjustment step). This happens several successive times, because the 2420 blocks are inside the 12,096 blocks buffer for 5 to 6 updated intervals. After that, the BSL will be back at 1 MB within a short time. The solution of PR https://github.com/jgarzik/bip100/pull/14 seems more appropriate to me, since votes of one adjustment interval do not stay in the memory buffer for another 5 to 6 adjustment intervals.
