### ISSUE TITLE
Voting string

### ISSUE THREAD

**Issue by btcdrak** [jgarzik/bip100#8]
I suggest changing from votes from a string "/BVnnnnnnnn/" to a 4 byte unsigned integer where the integer is the blocksize in bytes. There's no need to take up so much space in the coinbase field.

**Comment by rustyrussell** [comment]
Maybe 5 bytes, to be safe.

But otherwise the current parsing is problematic. Should insist that if it's not a valid u64, it's ignored (not to nearest limit). Would suggest ignored if out of bounds, too, but I guess some people want to nail 8M in there?

**Comment by btcdrak** [comment]
@rustyrussell https://github.com/jgarzik/bip100/pull/11

**Comment by eordano** [comment]
Yes, agree! The current format, `/B\d+[M]{0,1}/` is not easy to parse and distinguish from other data that could live along in the coinbase scriptSig. A delimiter, not making the `M` optional, or a fixed length are some of the possible solutions.

**Comment by macksko415** [comment]
flll_9in{}bv

**Comment by 1MichaS1** [comment]
I propose voting by RegExp /B0x[0-9a-f]{2}/, where RegExp [0-9a-f]{2} is an 8-bit number denoting an exponent (similar to Pieter Wuille's format in "https://gist.github.com/sipa/c65665fc360ca7a176a6"):
Vote = floor(2^(8_bit_number / 16) \* 1,000,000) bytes.
This provides a range from 1 Mbyte to 62.8 GBytes in incremental steps of 4.4%, i.e. the first votes are
2^(0/16) = 1,000,000 bytes
2^(1/16) = 1,044,273 bytes
2^(2/16) = 1,090,507 bytes
  ...
2^(255/16) = 62,757,488,603 bytes

This is neat because it covers a HUGE range with only 8 bits, whereas the 4.4% granularity is absolutely fine enough. (in the user interface/config file the miner could still specify a human readable number like 2,345,678 Mbytes, and the SW would then round to the nearest number on that "exponential resolution grid" - in this example 2,345,678 would become 2,378,414 bytes acc. to 8-bit-exponent = 20 = 0x14).

Formula to convert the human readable byte value into the 8-bit exponent:

The_8_bit_exponent = floor(log(value_in_bytes/1e6)/log(2)*16 + 0.5)

**Comment by 1MichaS1** [comment]
Why not putting that 8-bit exponent I mentioned before into the block header's version number (e.g. the second most significant byte of the 32-bit-version number field). 32bits are anyway too much for the version number, and that byte is never used. Gavin A. mentioned in his BIP101 github mediawiki that having it in the coinbase SigScript is a disadvantage:

Quote:
“[...] [Having BIP100's vote in the coinbase scriptSig] is more complex to implement [than BIP101's solution to only have a modification in the header], because [with BIP100] the maximum allowed size for a block depends on information contained in coinbase transactions from previous blocks (which may not be immediately known if block contents are being fetched out-of-order in a 'headers-first' mode)”
